Error occurred for archi_num: 3172. Error: Traceback (most recent call last):
  File "/home/younan/project_calibration/project_calibration/main.py", line 168, in <module>
    preds, pred_classes,targets = get_preds_and_targets(net, test_loader, device)
  File "/home/younan/project_calibration/project_calibration/main.py", line 37, in get_preds_and_targets
    output_tuple = model(data)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/xautodl/models/cell_infers/tiny_network.py", line 54, in forward
    feature = self.stem(inputs)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation

Error occurred for archi_num: 3106. Error: Traceback (most recent call last):
  File "/home/younan/project_calibration/project_calibration/main.py", line 168, in <module>
    preds, pred_classes,targets = get_preds_and_targets(net, test_loader, device)
  File "/home/younan/project_calibration/project_calibration/main.py", line 37, in get_preds_and_targets
    output_tuple = model(data)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/xautodl/models/cell_infers/tiny_network.py", line 54, in forward
    feature = self.stem(inputs)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

Error occurred for archi_num: 3107. Error: Traceback (most recent call last):
  File "/home/younan/project_calibration/project_calibration/main.py", line 168, in <module>
    preds, pred_classes,targets = get_preds_and_targets(net, test_loader, device)
  File "/home/younan/project_calibration/project_calibration/main.py", line 37, in get_preds_and_targets
    output_tuple = model(data)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/xautodl/models/cell_infers/tiny_network.py", line 54, in forward
    feature = self.stem(inputs)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

Error occurred for archi_num: 3589. Error: Traceback (most recent call last):
  File "/home/younan/project_calibration/project_calibration/main.py", line 168, in <module>
    preds, pred_classes,targets = get_preds_and_targets(net, test_loader, device)
  File "/home/younan/project_calibration/project_calibration/main.py", line 37, in get_preds_and_targets
    output_tuple = model(data)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/xautodl/models/cell_infers/tiny_network.py", line 54, in forward
    feature = self.stem(inputs)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/younan/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

Error occurred for archi_num: ['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']. Error: usage: main.py [-h] [--csv_file CSV_FILE] [--bin_sizes BIN_SIZES] [--archi_num ARCHI_NUM] [--image_dataset IMAGE_DATASET] [--api_type API_TYPE]
               [--post_temp POST_TEMP] [--device DEVICE]
main.py: error: argument --archi_num: invalid int value: "['7819', '7821', '7826', '7827', '7828', '7831', '7834', '7841', '7843', '7844', '7845', '7847', '7848', '7850', '7855', '7856', '7857', '7860', '7863', '7865', '7866', '7868', '7880', '7881', '7885', '7886', '7887', '7891', '7897', '7898', '7900', '7901', '7906', '7908', '7913', '7914', '7918', '7921', '7924', '7925', '7926', '7928', '7931', '7934', '7935', '7940', '7942', '7943', '7944', '7945', '7947', '7951', '7958', '7961', '7963', '7966', '7968', '7975', '7976', '7978', '7986', '7987', '7990', '7994', '7997', '7999', '8002', '8004', '8006', '8007', '8012', '8014', '8020', '8030', '8035', '8037', '8049', '8052', '8056', '8059', '8063', '8072', '8073', '8074', '8075', '8078', '8081', '8082', '8085', '8086', '8092', '8093', '8094', '8095', '8097', '8101', '8102', '8104', '8107', '8109', '8110', '8111', '8114', '8116', '8117', '8118', '8119', '8120', '8124', '8129', '8132', '8135', '8142', '8143', '8144', '8148', '8149', '8150', '8151', '8154', '8155', '8156', '8160', '8161', '8162', '8163', '8166', '8170', '8174', '8175', '8180', '8182', '8184', '8188', '8190', '8194', '8196', '8198', '8202', '8203', '8209', '8212', '8216', '8217', '8219', '8221', '8223', '8227', '8228', '8234', '8239', '8242', '8244', '8245', '8248', '8254', '8257', '8258', '8259', '8260', '8261', '8262', '8272', '8273', '8277', '8282', '8283', '8284', '8286', '8287', '8290', '8291', '8294', '8295', '8300']"

